Helm: No longer attempt to use secrets.name within values.yaml.
This was causing the error:
Error: failed to parse chart/values.yaml: error converting YAML to JSON: yaml: invalid map key: map[interface {}]interface {}{".Values.secrets.name":interface {}(nil)}